In [ ]:
import pandas as pd

In [3]:
df1 = pd.read_csv("Dim_Employee.csv")
df1.head()

  EmployeeID    EmployeeName Gender            Department        JobTitle
0      E0002   Phan Thị Vinh    Nam              Sản xuất     Giám sát ca
1      E0091  Phan Văn Trang     Nữ              Sản xuất     Giám sát ca
2      E0018   Đỗ Thanh Vinh    Nam              Sản xuất     Giám sát ca
3      E0134   Huỳnh Văn Anh     Nữ               Kho vận   Nhân viên kho
4      E0019   Võ Thị Phương     Nữ  Kiểm định chất lượng  Chuyên viên QC

In [5]:
df1.isna().sum

<bound method DataFrame.sum of      EmployeeID  EmployeeName  Gender  Department  JobTitle
0         False         False   False       False     False
1         False         False   False       False     False
2         False         False   False       False     False
3         False         False   False       False     False
4         False         False   False       False     False
..          ...           ...     ...         ...       ...
295       False         False   False       False     False
296       False         False   False       False     False
297       False         False   False       False     False
298       False         False   False       False     False
299       False         False   False       False     False

[300 rows x 5 columns]>

In [6]:
df1.duplicated().sum()

np.int64(0)

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EmployeeID    300 non-null    object
 1   EmployeeName  300 non-null    object
 2   Gender        300 non-null    object
 3   Department    300 non-null    object
 4   JobTitle      300 non-null    object
dtypes: object(5)
memory usage: 11.8+ KB

In [8]:
df2 = pd.read_csv("Fact_Hires.csv")
df2.head()

  EmployeeID    HireDate
0      E0002  2021-01-01
1      E0091  2021-02-01
2      E0018  2021-02-05
3      E0134  2021-02-09
4      E0019  2021-02-15

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  300 non-null    object
 1   HireDate    300 non-null    object
dtypes: object(2)
memory usage: 4.8+ KB

In [10]:
#chuyen HireDate sang kieu du lieu date
df2["HireDate"] = pd.to_datetime(df2["HireDate"], errors="coerce")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  300 non-null    object
 1   HireDate    300 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 4.8+ KB

In [11]:
df2.head()

  EmployeeID   HireDate
0      E0002 2021-01-01
1      E0091 2021-02-01
2      E0018 2021-02-05
3      E0134 2021-02-09
4      E0019 2021-02-15

In [12]:
df3 = pd.read_csv("Fact_Termination.csv")
df3.head()

  EmployeeID TerminationDate   TerminationReason  LastBaseSalaryVND
0      E0056      2021-05-12            Thu nhập           14180587
1      E0164      2023-03-18            Thu nhập           10098595
2      E0171      2023-03-21       Ca kíp/Áp lực           17385353
3      E0037      2023-08-03  Cơ hội nghề nghiệp           16944585
4      E0289      2023-09-15  Cơ hội nghề nghiệp           10970919

In [13]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         60 non-null     object
 1   TerminationDate    60 non-null     object
 2   TerminationReason  60 non-null     object
 3   LastBaseSalaryVND  60 non-null     int64
dtypes: int64(1), object(3)
memory usage: 2.0+ KB

# SAVE FILE

In [14]:
df1.to_csv("Dim_Employee.csv", index=False)
df2.to_csv("Fact_Hires.csv", index=False)
df3.to_csv("Fact_Termination.csv", index=False)